### ISSUE TITLE
Swap  #ffffff background for darker white.

### ISSUE THREAD

**Issue by bmartinez287** [ddev/ddev.com#117]
<img width="1327" alt="Screen Shot 2023-10-15 at 10 36 31 PM" src="https://github.com/ddev/ddev.com/assets/39039024/96771eb9-71d1-4a3e-abd3-f5a974c3898e">
<img width="1100" alt="Screen Shot 2023-10-15 at 10 28 39 PM" src="https://github.com/ddev/ddev.com/assets/39039024/41051102-78f9-4a59-829d-e34688b68d63">
<img width="1201" alt="Screen Shot 2023-10-15 at 10 27 22 PM" src="https://github.com/ddev/ddev.com/assets/39039024/c3881d02-de96-450b-abe6-36ea001db874">

So I was wondering if we could swap the current white background from #ffffff which is the purest white to one that is a bit darker like the colors above.
Thoughts?

**Comment by mattstein** [comment]
What’s the issue here?

**Comment by bmartinez287** [comment]
Well, mostly to lower the brightness. It's rare to find the whitest white as a background. But it could be that it works as design, if so we can close it.

**Comment by mattstein** [comment]
I intentionally kept it bright and contrasty, and I’m not sure how to quantify _rare_ being a problem or an accurate claim. google.com, github.com, and cloudflare.com use full `#fff`, and I’m just randomly picking sites I can think of being white-backgrounded.

Just because I used it intentionally doesn’t mean anything, but changing it to lower brightness seems like a solution without a problem.

**Comment by bmartinez287** [comment]
Sounds good.
